### ISSUE TITLE
Could not load type "cmf_media_image"

### ISSUE THREAD

**Issue by samanmohamadi** [symfony-cmf/media-bundle#156] opened 2016-09-10 21:48 UTC
Symfony 3 

when trying to create an image in admin panel I get this :
**Could not load type "cmf_media_image"**

PHPCR is also enabled.

```
class ImageAdmin extends AbstractAdmin
{
    protected function configureFormFields(FormMapper $formMapper)
    {
        $formMapper
            ->add('image', 'cmf_media_image', array('required' => false))
        ;
    }
}

```

```
cmf_media:
    persistence:
        phpcr:
            enabled:         true
            manager_name:    ~
            media_basepath:  "%cmf_media.persistence.phpcr.media_basepath%"
            media_class:     Symfony\Cmf\Bundle\MediaBundle\Doctrine\Phpcr\Media
            file_class:      Symfony\Cmf\Bundle\MediaBundle\Doctrine\Phpcr\File
            directory_class: Symfony\Cmf\Bundle\MediaBundle\Doctrine\Phpcr\Directory
            image_class:     Symfony\Cmf\Bundle\MediaBundle\Doctrine\Phpcr\Image
            event_listeners:
                stream_rewind:    true
                image_dimensions: true
                imagine_cache:    auto
```

**Comment by ElectricMaxxx** [comment] 2017-01-05 20:02
Which Symfony Version are you using?
As this bundle is currently not maintained the bundle does not support Symfony 3.x at all. So form type can be a problem.

**Comment by ElectricMaxxx** [comment] 2017-08-05 09:32
I can't reproduce that issue so i will close it, please give some feedback if the issue is still there.

**Closed by ElectricMaxxx** 2017-08-05 09:32 UTC
